export const ARENA = 'arena'
export const GAME_OVER = 'gameOver'
export const PRELOAD = 'preload'
export const STARTER = 'starter'
export const TITLE = 'title'
export const UPGRADE = 'upgrade'
export const WAVE_START = 'waveStart'
